server:
  port: 80
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    # 当前数据源操作类型
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.99.143.9:3306/xxx?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: xxx
  application:
    name: lingyunshop-service
  cloud:
   nacos:
      discovery:
        server-addr:  xxx
        namespace: xxx
        group: LINGYUNSHOP_SERVICE
mybatis:
  mapper-locations: classpath*:/mapper/*.xml

dubbo:
  consumer:
    timeout: 600000
  scan:
    #自己向外提供服务的service的包地址
    base-packages: com.lingyun.service
  protocol:
    #dubbo协议
    name: dubbo
    #dubbo 协议端口（ -1 表示自增端口，从 20880 开始)
    port: -1
  #注册到nacos注册中心
  registry:
    address: xxx
    register: true
    subscribe: true
